"""
Alloy solver and instance converter for UML-BESSER models.

This module contains:
- the translation from UML-BESSER class diagrams and OCL constraints into Alloy,
- the orchestration of the Alloy Analyzer to generate bounded instances as
  witnesses of satisfiability/consistency,
- the translation of Alloy instances back into UML object diagrams.
"""

import logging
import os
import re
import tempfile
import xml.etree.ElementTree as ET
from typing import Any

from besser.BUML.metamodel.structural import DomainModel
from besser.generators.alloy.alloy_generator import AlloyGenerator
from besser.utilities.buml_code_builder.domain_model_builder import domain_model_to_code
from besser.generators.alloy.instance_generator.alloy_solver_utils import (
    DATE_SIG_PATTERN,
    execute_alloy_analyzer,
    get_class_name,
    get_date_value,
    get_enum_value,
    get_primitive_value,
    is_domain_class_name,
    is_enum_value,
    parse_receipt,
    remove_class_prefix,
    resolve_first_instance_xml,
)
from besser.generators.alloy.translate_ocl_alloy import (
    EnumReferenceError,
)
from besser.utilities.web_modeling_editor.backend.services.converters.buml_to_json.object_diagram_converter import (
    object_buml_to_json,
)

logger = logging.getLogger(__name__)

class AlloyToBesserConverter:
    """Converts Alloy XML instances to BESSER objects."""

    def __init__(self, xml_file: str):
        """
        Initializes the converter with the given Alloy XML file.

        Args:
            xml_file: Path to Alloy XML file
        """
        self.xml_file = xml_file
        self.tree = ET.parse(xml_file)
        self.root = self.tree.getroot()

        # Data structures to store parsed information
        self.signatures = {}  # sig_id -> {label, atoms}
        self.fields = {}  # field_id -> {label, parent_id, tuples}
        self.atoms_by_sig = {}  # sig_label -> [atoms]
        self.builtin_sigs = {'seq/Int', 'Int', 'String', 'univ', 'boolean/Bool',
                            'boolean/True', 'boolean/False'}

    def parse_xml(self):
        """Parses the Alloy XML file and extracts signatures, fields, and atoms."""

        # Parse signatures
        for sig in self.root.findall('.//sig'):
            sig_id = sig.get('ID')
            sig_label = sig.get('label')
            parent_id = sig.get('parentID')

            # Ignore built-in signatures
            if sig_label in self.builtin_sigs:
                continue

            atoms = [atom.get('label') for atom in sig.findall('atom')]

            self.signatures[sig_id] = {
                'label': sig_label,
                'atoms': atoms,
                'builtin': sig.get('builtin') == 'yes',
                'parent_id': parent_id,
            }

            # Organize atoms by signature label
            if not self.signatures[sig_id]['builtin']:
                self.atoms_by_sig[sig_label] = atoms

        # Parse fields
        for field in self.root.findall('.//field'):
            field_id = field.get('ID')
            field_label = field.get('label')
            parent_id = field.get('parentID')

            tuples = []
            for tuple_elem in field.findall('tuple'):
                atoms = [atom.get('label') for atom in tuple_elem.findall('atom')]
                if len(atoms) >= 2:
                    tuples.append((atoms[0], atoms[1]))

            self.fields[field_id] = {
                'label': field_label,
                'parent_id': parent_id,
                'tuples': tuples
            }

    def _date_sig_label(self) -> str | None:
        """Returns the label of the 'date' signature (e.g., 'this/date') if it exists."""
        for sig_label in self.atoms_by_sig:
            if get_class_name(sig_label) == "date":
                return sig_label
        return None

    def is_date_value(self, atom_label: str) -> bool:
        """
        Determines if an atom represents a date value.

        Recognizes both literals of the form ``dMMDDYYYY`` (as emitted by OCL constraints)
        and free atoms of the ``date`` signature generated by Alloy (e.g., ``date$0``, ``date$01``,
        or other strings).
        """
        base = atom_label.split("$")[0]
        if DATE_SIG_PATTERN.match(base):
            return True
        date_sig_label = self._date_sig_label()
        return bool(date_sig_label and atom_label in self.atoms_by_sig[date_sig_label])

    def is_object_reference(self, atom_label: str) -> bool:
        """
        Determines if an atom is a reference to another domain object.
        Args:
            atom_label: atom label to check

        Returns:
            True if it is a reference to an object, False if it is primitive
        """
        # Domain objects are represented with format ClassName$N
        if '$' in atom_label:
            base = atom_label.split('$')[0]

            # Exclude special types and types that are not domain objects
            if base in ['str', 'pepe', 'Position'] or base.startswith('ENUM_'):
                return False

            # Check if it exists in atoms_by_sig with the prefix this/
            for sig_label in self.atoms_by_sig:
                class_name = get_class_name(sig_label)
                if (class_name == base
                        and atom_label in self.atoms_by_sig[sig_label]
                        and class_name not in ['str', 'Bool', 'True', 'False']):
                    return True
        return False

    def _pair_association_fields(self) -> dict[str, frozenset]:
        """
        Pairs the two ends of the same bidirectional association.

        The Alloy encoding represents a bidirectional association as two fields with exactly transposed
        sets of tuples. This mapping allows one to deduplicate only those two halves without collapsing
        distinct associations between the same pair of objects.
        """
        field_tuples: dict[str, set[tuple]] = {}
        for field_data in self.fields.values():
            label = field_data['label']
            field_tuples[label] = set(field_data['tuples'])

        used: set[str] = set()
        paired: dict[str, frozenset] = {}
        for field_label, tuples in field_tuples.items():
            if field_label in used or not tuples:
                continue

            transposed = {(to_atom, from_atom) for from_atom, to_atom in tuples}
            partner = None
            for other_label, other_tuples in field_tuples.items():
                if other_label in used or other_label == field_label or not other_tuples:
                    continue
                if other_tuples == transposed:
                    partner = other_label
                    break

            if partner:
                assoc = frozenset([field_label, partner])
                paired[field_label] = assoc
                paired[partner] = assoc
                used.update([field_label, partner])
            else:
                paired[field_label] = frozenset([field_label])

        return paired

    def _signature_depth(self, sig_id: str | None) -> int:
        """Returns the depth of *sig_id* in the inheritance tree."""
        depth = 0
        current_id = sig_id
        while current_id and current_id in self.signatures:
            parent_id = self.signatures[current_id].get('parent_id')
            if not parent_id or parent_id not in self.signatures:
                break
            depth += 1
            current_id = parent_id
        return depth

    def _leaf_class_for(self, atom_label: str) -> str | None:
        """Returns the most specific concrete class that contains *atom_label*."""
        containing = [sig for sig in self._domain_signatures if atom_label in sig['atoms']]
        if not containing:
            return None
        leaf_sig = max(
            containing,
            key=lambda sig: (sig['depth'], -len(sig['atoms']), sig['class_name'])
        )
        return leaf_sig['class_name']

    def generate_object_diagram_code(self) -> str:
        """
        Generates BUML code for the object diagram derived from the XML.

        Only the most specific concrete class of each atom is instantiated,
        inherited attributes are incorporated, and multiple associations
        between the same classes or objects are preserved.
        """
        code_lines = []

        # Identify the domain classes. The enumeration signatures should not
        # be materialized as objects.
        domain_classes = set()
        for sig_label, atoms in self.atoms_by_sig.items():
            if not sig_label.startswith("this/"):
                continue
            class_name = get_class_name(sig_label)
            if not is_domain_class_name(class_name):
                continue
            if atoms and all(is_enum_value(atom) for atom in atoms):
                continue
            domain_classes.add(class_name)

        self._domain_signatures = []
        for sig_id, sig_data in self.signatures.items():
            class_name = get_class_name(sig_data['label'])
            if class_name not in domain_classes:
                continue
            self._domain_signatures.append({
                'class_name': class_name,
                'atoms': set(sig_data['atoms']),
                'depth': self._signature_depth(sig_id),
            })

        created_objects = {}  # atom_label -> variable_name
        relations = []  # [(from_var, relation_name, to_atom, field_name), ...]

        for sig_label, atoms in self.atoms_by_sig.items():
            class_name = get_class_name(sig_label)

            if class_name not in domain_classes:
                continue

            for i, atom_label in enumerate(atoms):
                if self._leaf_class_for(atom_label) != class_name:
                    continue

                obj_var = f"{class_name.lower()}_{i}_obj"
                obj_name = atom_label.replace('$', '_')

                created_objects[atom_label] = obj_var
                attributes = {}

                # Traverse all fields to also include attributes and associations
                # inherited from ancestor classes.
                for field_data in self.fields.values():
                    field_name = field_data['label']
                    tuples = field_data['tuples']
                    attr_name = remove_class_prefix(field_name, class_name)

                    for tuple_from, tuple_to in tuples:
                        if tuple_from != atom_label:
                            continue

                        if self.is_date_value(tuple_to):
                            attributes[attr_name] = get_date_value(tuple_to)
                        elif self.is_object_reference(tuple_to):
                            relations.append((obj_var, attr_name, tuple_to, field_name))
                        elif is_enum_value(tuple_to):
                            enum_value = get_enum_value(tuple_to)
                            attributes[attr_name] = f'"{enum_value}"'
                        else:
                            attributes[attr_name] = get_primitive_value(tuple_to)

                attribute_mapping_parts = []
                for attr_name, attr_value in attributes.items():
                    attribute_mapping_parts.append(f"{attr_name!r}: {attr_value}")

                if attribute_mapping_parts:
                    code_lines.append(
                        f'{obj_var} = {class_name}("{obj_name}").attributes(**{{{", ".join(attribute_mapping_parts)}}}).build()'
                    )
                else:
                    code_lines.append(
                        f'{obj_var} = {class_name}("{obj_name}").build()'
                    )

        code_lines.append("")

        if relations:
            code_lines.append("# Set relations between objects")

        paired_fields = self._pair_association_fields()
        seen_links = set()
        deduplicated_relations = []
        for from_var, relation_name, to_atom, field_name in relations:
            if to_atom not in created_objects:
                continue
            to_var = created_objects[to_atom]
            assoc_id = paired_fields.get(field_name, frozenset([field_name]))
            canonical = (frozenset([from_var, to_var]), assoc_id)
            if canonical in seen_links:
                continue
            seen_links.add(canonical)
            deduplicated_relations.append((from_var, relation_name, to_atom))

        relations = deduplicated_relations

        # Group relations by (from_var, relation_name) to handle multiplicity 'many'
        grouped_relations = {}
        for from_var, relation_name, to_atom in relations:
            if to_atom in created_objects:
                key = (from_var, relation_name)
                if key not in grouped_relations:
                    grouped_relations[key] = []
                grouped_relations[key].append(created_objects[to_atom])

        for (from_var, relation_name), to_vars in grouped_relations.items():
            unique_targets = sorted(set(to_vars))
            if len(unique_targets) == 1:
                code_lines.append(
                    f"setattr({from_var}, {relation_name!r}, {unique_targets[0]})"
                )
            else:
                targets_expr = ", ".join(unique_targets)
                code_lines.append(
                    f"setattr({from_var}, {relation_name!r}, {{{targets_expr}}})"
                )

        if relations:
            code_lines.append("")

        code_lines.append("# Object Model instance")
        all_objects = ", ".join(created_objects.values())
        code_lines.append("object_model: ObjectModel = ObjectModel(")
        code_lines.append('    name="Object_Diagram",')
        code_lines.append(f"    objects={{{all_objects}}}")
        code_lines.append(")")
        return "\n".join(code_lines)

    def to_json(self, reference_class_model: dict[str, Any]) -> dict[str, Any]:
        """
        Converts the parsed Alloy instance into the frontend ObjectDiagram JSON format.

        Args:
            reference_class_model: Reference class diagram JSON, used to map attribute types.

        Returns:
            Dictionary representing the object diagram in JSON format.
        """
        code = self.generate_object_diagram_code()
        return object_buml_to_json(code, reference_class_model)

def alloy_xml_to_frontend_object_model(
    xml_instance_path: str, reference_class_model: dict[str, Any]
) -> dict[str, Any]:
    """
    Converts an Alloy instance XML file into the frontend ObjectDiagram JSON.

    The Alloy instance is received in XML format. The result is provided
    in the JSON format for ObjectDiagram, expected by the frontend.
    """
    converter = AlloyToBesserConverter(xml_instance_path)
    converter.parse_xml()
    return converter.to_json(reference_class_model)


class BUMLModelIntegrator:
    """Integrates an original BUML model with an object diagram generated from Alloy."""

    def __init__(self, original_buml_content: str, xml_instance_file: str):
        """
        Initializes the integrator.

        Args:
            original_buml_content: Source code of the original BUML file (class diagram)
            xml_instance_file: Path to the Alloy instance XML file
        """
        self.xml_instance_file = xml_instance_file
        self.original_content = original_buml_content

    def extract_structural_model_section(self) -> str:
        """
        Extracts the structural model section (class diagram) from the original BUML content.

        Returns:
            The code of the structural model section.
        """
        patterns = [
            r'################\s*\n#\s*OBJECT MODEL\s*#',
            r'##############\s*\n\s*from besser\.BUML\.metamodel\.object',
            r'######################\s*\n#\s*PROJECT DEFINITION\s*#'
        ]

        end_pos = len(self.original_content)
        for pattern in patterns:
            match = re.search(pattern, self.original_content, re.IGNORECASE)
            if match:
                end_pos = min(end_pos, match.start())

        structural_section = self.original_content[:end_pos].rstrip()
        return structural_section

    def extract_project_section(self) -> str:
        """
        Extracts the project definition section from the original BUML content if it exists.

        Returns:
            The code of the project section or an empty string if not found.
        """
        pattern = r'######################\s*\n#\s*PROJECT DEFINITION\s*#\s*\n######################\s*\n(.*)'
        match = re.search(pattern, self.original_content, re.DOTALL)

        if match:
            project_section = match.group(0).strip()

            models_pattern = r'(models=\[)([^\]]+)(\])'

            def replace_models(match):
                prefix = match.group(1)
                models_list = match.group(2).strip()
                suffix = match.group(3)

                if 'object_model' in models_list:
                    return match.group(0)

                if models_list:
                    return f"{prefix}{models_list}, object_model{suffix}"
                return f"{prefix}object_model{suffix}"

            project_section = re.sub(models_pattern, replace_models, project_section)

            return project_section
        return ""

    def generate_integrated_model(self, output_file: str | None = None) -> str:
        """
        Generates the complete integrated BUML model.

        Args:
            output_file: File to save the model (optional)

        Returns:
            The code of the integrated model.
        """
        structural_section = self.extract_structural_model_section()

        converter = AlloyToBesserConverter(self.xml_instance_file)
        converter.parse_xml()
        object_diagram_code = converter.generate_object_diagram_code()

        project_section = self.extract_project_section()

        integrated_lines = []

        integrated_lines.append(structural_section)
        integrated_lines.append("")
        integrated_lines.append("")

        integrated_lines.append("################")
        integrated_lines.append("# OBJECT MODEL #")
        integrated_lines.append("################")
        integrated_lines.append("")
        integrated_lines.append("from besser.BUML.metamodel.object import ObjectModel")
        integrated_lines.append("import datetime")
        integrated_lines.append("")
        integrated_lines.append(object_diagram_code)
        integrated_lines.append("")
        integrated_lines.append("")

        if project_section:
            integrated_lines.append(project_section)

        integrated_model = "\n".join(integrated_lines)

        if output_file:
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(integrated_model)

        return integrated_model


#----------------------------------------------------------------------
# Alloy invocation and satisfiability checking
#----------------------------------------------------------------------

class AlloySolver:

    def __init__(self, model: DomainModel, output_dir: str | None = None, scope: int = 5):
        if output_dir is None:
            self._temp_dir = tempfile.TemporaryDirectory(prefix="alloy_")
            output_dir = self._temp_dir.name
        else:
            self._temp_dir = None
        self.scope = scope
        self.model = model
        self.output_dir = output_dir
        generator = AlloyGenerator(model=self.model, output_dir=output_dir, scope=scope)
        generator.generate()
        self.file = os.path.join(output_dir, "model.als")

    def check_consistency(
        self,
        output_type: str = "json",
    ) -> bool | None:
        """Execute the Alloy Analyzer and check model satisfiability.

        Returns ``True`` if satisfiable (SAT), ``False`` if unsatisfiable (UNSAT),
        or ``None`` when the satisfiability could not be determined (error).

        As a side effect, this method populates the following state attributes,
        which consumers can read for additional data:
        - ``self.satisfiable``: ``bool`` or ``None`` (same as the return value)
        - ``self.command_name``: name of the first Alloy run/check command
        - ``self.solutions``: list of solutions (instances) found by the Analyzer
        - ``self.exec_output_dir``: directory where the Analyzer placed its output
        - ``self.last_error``: structured error dict when the check fails (``None``
          on success), with keys ``sat``, ``isValid``, ``message``, ``errors``,
          ``warnings``.
        """
        self.exec_output_dir = os.path.join(self.output_dir, "alloy_exec_output")
        self.satisfiable = None
        self.command_name = None
        self.solutions = []
        self.last_error = None
        try:
            result, error = execute_alloy_analyzer(
                self.file, self.exec_output_dir, output_type=output_type
            )
        except (EnumReferenceError, ValueError) as exc:
            self.last_error = {
                "sat": None,
                "isValid": False,
                "message": str(exc),
                "errors": [str(exc)],
                "warnings": [],
            }
            return None
        if error:
            self.last_error = error
            return None
        parsed, parse_error = parse_receipt(self.exec_output_dir, result)
        if parse_error:
            self.last_error = parse_error
            return None
        sat, command_name, solutions = parsed
        self.satisfiable = sat
        self.command_name = command_name
        self.solutions = solutions
        return sat

    def generate_instance_xml(self) -> str | None:
        """Run the satisfiability check and resolve the first instance XML.

        Returns the path to the XML file, or ``None`` if unsatisfiable.
        """
        satisfiable = self.check_consistency(output_type="xml")
        if satisfiable is not True:
            return None
        return resolve_first_instance_xml(self.exec_output_dir, self.solutions)

    def generate_object_diagram_code(
        self,
        xml_instance_path: str | None = None,
    ) -> str | None:
        """Generates BUML object-diagram code from a satisfying Alloy instance."""
        if xml_instance_path is None:
            xml_instance_path = self.generate_instance_xml()
            if not xml_instance_path:
                return None
        converter = AlloyToBesserConverter(xml_instance_path)
        converter.parse_xml()
        return converter.generate_object_diagram_code()

    def generate_object_diagram_json(
        self,
        reference_class_model: dict[str, Any],
        xml_instance_path: str | None = None,
    ) -> dict[str, Any] | None:
        """Generates the frontend ObjectDiagram JSON from a satisfying Alloy instance."""
        if xml_instance_path is None:
            xml_instance_path = self.generate_instance_xml()
            if not xml_instance_path:
                return None
        converter = AlloyToBesserConverter(xml_instance_path)
        converter.parse_xml()
        return converter.to_json(reference_class_model)

    def generate_integrated_buml_model(
        self,
        xml_instance_path: str | None = None,
    ) -> str | None:
        """Generates a BUML script combining the original class diagram with the
        object diagram derived from a satisfying Alloy instance."""
        if xml_instance_path is None:
            xml_instance_path = self.generate_instance_xml()
            if not xml_instance_path:
                return None
        tmp_buml = os.path.join(self.output_dir, "_tmp_buml_content.py")
        domain_model_to_code(model=self.model, file_path=tmp_buml)
        try:
            with open(tmp_buml, "r", encoding="utf-8") as f:
                original_buml_content = f.read()
        finally:
            if os.path.exists(tmp_buml):
                os.unlink(tmp_buml)
        integrator = BUMLModelIntegrator(original_buml_content, xml_instance_path)
        return integrator.generate_integrated_model()


def run_alloy_sat_validation(
    buml_model: DomainModel,
    all_warnings: list[str] | None = None,
    scope: int = 5,
    output_type: str = "json",
    output_dir: str | None = None,
) -> tuple[tuple[Any, ...] | None, dict[str, Any] | None, str]:
    """Translate a BUML class diagram + OCL constraints into Alloy, execute
    the Alloy Analyzer, and return the consistency-check result.

    This is a thin wrapper around :meth:`AlloySolver.check_consistency` (the
    single source of truth for the Alloy execution). It builds the solver, folds
    in the web-layer ``warnings``, and exposes the result in the legacy
    ``(parsed_data, error_response, exec_output_dir)`` shape where
    *parsed_data* is ``(sat, command_name, solutions)``.
    """
    warnings = all_warnings or []
    try:
        solver = AlloySolver(buml_model, scope=scope, output_dir=output_dir)
    except ValueError as exc:
        msg = str(exc)
        return None, {
            "sat": None,
            "isValid": False,
            "message": msg,
            "errors": [msg] if msg else [],
            "warnings": warnings,
        }, output_dir or "output"
    solver.check_consistency(output_type=output_type)
    if solver.satisfiable is None:
        return None, {**solver.last_error, "warnings": warnings}, solver.exec_output_dir
    return (
        (solver.satisfiable, solver.command_name, solver.solutions),
        None,
        solver.exec_output_dir,
    )
